add_subdirectory(test_test)
add_subdirectory(alarm_test)
add_subdirectory(flash_test_raw)
add_subdirectory(flash_test_no_os)
add_subdirectory(panic_test)
if(FREE_RTOS_DYNAMIC)
    add_subdirectory(freertos_dynamic_test)
endif()
if(FREE_RTOS_STATIC)
    add_subdirectory(freertos_static_test)
    add_subdirectory(freertos_hw_timer_test)
endif()
if(FREE_RTOS_STATIC AND FREE_RTOS_DYNAMIC)
    add_subdirectory(freertos_multitask_test)
endif()
add_subdirectory(seeedstudio_rp2040_test)